/**
 * Global leaderboard behind a swappable driver, like Ads, Payments and
 * CloudSave. Ranked by **campaign stars** (0-1500): the number the home card
 * already shows, so a player's board position matches what they see every
 * time they open the game, and replaying an old level for its missing third
 * star climbs the board. "Levels cleared" was rejected: everyone who finishes
 * ties at 500 and it rewards rushing past levels rather than playing well.
 *
 * Storage and identity are the platform's - no server of ours, per the v1
 * no-backend decision:
 *   Android  Play Games Services leaderboards (same sign-in as cloud save,
 *            so the two share one account and one consent prompt)
 *   iOS      Game Center (GameKit) - a different API from the iCloud store
 *            cloud save uses, but the same native plugin
 *   Web      nothing; the button never appears
 *
 * Scores are whatever the client submits: with no backend there is no way to
 * verify them, so a determined cheater can post any total. That is normal for
 * a casual puzzle and the stakes are bragging rights. If it ever matters, the
 * boards are deterministic, so a server could replay a submitted move list and
 * verify the solve exactly (see docs/AUDIT.md E5).
 */
import { capacitorGlobal, isNativeApp, platform } from './Platform';

/**
 * Campaign level a player must have *reached* before the board is offered.
 * Deep enough that a first score is worth posting (roughly two and a bit
 * chapters in) and that the sign-in prompt lands on an invested player, not a
 * curious one who opened the game a minute ago.
 */
export const LEADERBOARD_UNLOCK_LEVEL = 45;

/** Pure, so the gate is unit-testable and stated in exactly one place. */
export function leaderboardUnlocked(highestLevel: number): boolean {
  return highestLevel >= LEADERBOARD_UNLOCK_LEVEL;
}

/**
 * Board ids.
 *
 * Android: generated by Play Console → Play Games Services → Leaderboards
 * (looks like `CgkI...`). Until it exists the placeholder below keeps the
 * feature reporting itself unavailable, so no button appears that could not
 * work - the same guard the AdMob sample ids use.
 *
 * iOS: *you* choose this string in App Store Connect → Game Center →
 * Leaderboards, so it is already final; the board must be created with this
 * exact id, score format "Integer", sort order "High to Low".
 */
export const LEADERBOARD_IDS = {
  android: 'PLACEHOLDER_PLAY_GAMES_LEADERBOARD_ID',
  ios: 'prismpotions.stars',
} as const;

const PLACEHOLDER_PREFIX = 'PLACEHOLDER';

export type ShowOutcome =
  /** The platform's board UI opened. */
  | 'shown'
  /** The player declined the platform sign-in; not an error. */
  | 'signed-out'
  | 'unavailable';

export interface LeaderboardDriver {
  readonly name: 'none' | 'simulated' | 'native';
  /** Resolves whether a board can be used at all here. Never rejects. */
  isAvailable(): Promise<boolean>;
  /** Post a score. Silent no-op when signed out - never nags mid-game. */
  submitScore(score: number): Promise<void>;
  /** Open the platform's board UI, signing in first if the player agrees. */
  show(): Promise<ShowOutcome>;
}

// ------------------------------------------------------------------ drivers
/** Plain web: no platform account to rank against. */
export class NoLeaderboardDriver implements LeaderboardDriver {
  readonly name = 'none';
  async isAvailable(): Promise<boolean> { return false; }
  async submitScore(): Promise<void> { /* nowhere to post */ }
  async show(): Promise<ShowOutcome> { return 'unavailable'; }
}

/**
 * Development stand-in (`?lb=sim`): available, accepts scores, and reports a
 * successful open so the unlock, submit and button flows can be exercised in
 * a browser without a Play Games project. `?lb=sim-out` simulates a player
 * who declines the sign-in.
 */
export class SimulatedLeaderboardDriver implements LeaderboardDriver {
  readonly name = 'simulated';
  constructor(private readonly signedOut = false) {}
  async isAvailable(): Promise<boolean> { return true; }
  async submitScore(score: number): Promise<void> {
    console.debug('[leaderboard] would submit', score);
  }
  async show(): Promise<ShowOutcome> {
    await new Promise((r) => setTimeout(r, 400));
    return this.signedOut ? 'signed-out' : 'shown';
  }
}

/**
 * The native bridge. Both methods live on the same Capacitor plugin as cloud
 * save (`CloudSave`): on Android they need the identical Play Games sign-in,
 * so splitting them into a second plugin would mean maintaining two copies of
 * the auth handling. The plugin signs in on demand inside `showLeaderboard`
 * and stays silent in `submitLeaderboardScore`.
 */
interface LeaderboardPlugin {
  /** Not `isAvailable` - that one answers for cloud save, which on iOS is a
   *  different service (iCloud) from the leaderboard's (Game Center). */
  isLeaderboardAvailable(): Promise<{ available: boolean }>;
  submitLeaderboardScore(options: { leaderboardId: string; score: number }): Promise<void>;
  showLeaderboard(options: { leaderboardId: string }): Promise<{ shown: boolean }>;
}

function nativePlugin(): LeaderboardPlugin | null {
  const plugin = capacitorGlobal()?.Plugins?.CloudSave as LeaderboardPlugin | undefined;
  return plugin && typeof plugin.showLeaderboard === 'function' ? plugin : null;
}

export class NativeLeaderboardDriver implements LeaderboardDriver {
  readonly name = 'native';
  private readonly id = platform() === 'ios' ? LEADERBOARD_IDS.ios : LEADERBOARD_IDS.android;

  async isAvailable(): Promise<boolean> {
    if (!isNativeApp()) return false;
    if (this.id.startsWith(PLACEHOLDER_PREFIX)) {
      console.warn('[leaderboard] board id is still a placeholder; hiding the feature');
      return false;
    }
    const plugin = nativePlugin();
    if (!plugin) return false;
    try {
      return (await plugin.isLeaderboardAvailable()).available;
    } catch {
      return false;
    }
  }

  async submitScore(score: number): Promise<void> {
    const plugin = nativePlugin();
    if (!plugin) return;
    try {
      await plugin.submitLeaderboardScore({ leaderboardId: this.id, score });
    } catch (err) {
      // A failed post is not worth interrupting play for; the next win retries.
      console.warn('[leaderboard] submit failed', err);
    }
  }

  async show(): Promise<ShowOutcome> {
    const plugin = nativePlugin();
    if (!plugin) return 'unavailable';
    try {
      return (await plugin.showLeaderboard({ leaderboardId: this.id })).shown
        ? 'shown'
        : 'signed-out';
    } catch (err) {
      console.warn('[leaderboard] show failed', err);
      return 'unavailable';
    }
  }
}

export function pickLeaderboardDriver(): LeaderboardDriver {
  const sim = new URLSearchParams(window.location.search).get('lb');
  if (sim === 'sim' || sim === 'sim-out') return new SimulatedLeaderboardDriver(sim === 'sim-out');
  if (isNativeApp()) return new NativeLeaderboardDriver();
  return new NoLeaderboardDriver();
}

// ------------------------------------------------------------------ service
export class Leaderboard {
  private ready = false;
  /** Last score posted this session, so repeated wins do not re-post the same total. */
  private posted = -1;

  constructor(private readonly driver: LeaderboardDriver = new NoLeaderboardDriver()) {}

  /** Off the boot path; the game never waits on a platform service. */
  async init(): Promise<void> {
    try {
      this.ready = await this.driver.isAvailable();
    } catch {
      this.ready = false;
    }
  }

  /** Whether the platform can rank at all - separate from the level gate. */
  get available(): boolean {
    return this.ready;
  }

  get driverName(): string {
    return this.driver.name;
  }

  /** Post the player's star total. Cheap to call after every win. */
  async submit(score: number): Promise<void> {
    if (!this.ready || score <= this.posted) return;
    this.posted = score;
    await this.driver.submitScore(score);
  }

  show(): Promise<ShowOutcome> {
    if (!this.ready) return Promise.resolve('unavailable');
    return this.driver.show();
  }
}
